# Generated by Django 5.2.8 on 2025-11-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
