# Generated by Django 5.2.8 on 2025-11-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='sp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
