# Generated by Django 5.2.8 on 2025-11-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0003_alter_student_gp_alter_student_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behaviors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('xp', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'behaviors',
            },
        ),
    ]
