# Generated by Django 5.2.8 on 2025-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0005_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='charClass',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
