# Generated by Django 5.2.8 on 2025-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0006_skills_charclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='levelReq',
            field=models.IntegerField(default=0),
        ),
    ]
