# Generated by Django 5.2.8 on 2025-11-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0007_skills_levelreq'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
    ]
