# Generated by Django 5.2.8 on 2025-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0008_alter_skills_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='maxSP',
            field=models.IntegerField(default=0),
        ),
    ]
