# Generated by Django 5.2.8 on 2025-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0009_student_maxsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('sp', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('gp', models.IntegerField(default=0)),
                ('charClass', models.CharField(max_length=50)),
                ('randomStudent', models.BooleanField(default=False)),
            ],
        ),
    ]
