# Generated by Django 5.2.8 on 2025-11-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_hub', '0011_miracles_alter_randomevents_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miracles',
            name='charClass',
        ),
        migrations.RemoveField(
            model_name='miracles',
            name='randomStudent',
        ),
    ]
